### ISSUE TITLE
--main-text not applied to inflection tables

### ISSUE THREAD

**Issue by kuchenmitsahne** [RaitaroH/Jisho-DeepDark#1]
The inflection tables (accessible by clicking "Show inflections" on a verb or adjective entry such as [書く](http://jisho.org/word/%E6%9B%B8%E3%81%8F)) are nigh illegible, at least in the default color scheme where the `color` is `#222222` (from the original Jisho style) and `--second-background` is `#181818`.

![jisho_inflection_before](https://user-images.githubusercontent.com/25233413/32977493-7dc683e0-cbfc-11e7-8521-6dae9151a44a.png)

Here's my naïve solution:

    /*Inflection table*/
    table caption {
        color: var(--main-text) !important;
    }
    table tr th,
    table tr td {
        color: var(--main-text) !important;
    }

which [seems to work just fine for my purposes, although I haven't the first clue about CSS and I don't know if that breaks something else.

![jisho_inflection_after](https://user-images.githubusercontent.com/25233413/32977499-8cee10ae-cbfc-11e7-87a3-f486decede5b.png)

Other than this minor issue, this theme has been wonderful—thank you for creating this theme!

**Comment by RaitaroH** [comment]
Oh, I will fix this soon.
Btw, I am working to implement *.user.css functionality to work with Stylus. Please take a look. You can now install my themes directly from github.

**Comment by RaitaroH** [comment]
Also, wonderful fix too. Thank you.

**Comment by RaitaroH** [comment]
It was fixed.
